apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediciclient
  labels:
    app: mediciclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mediciclient
  template:
    metadata:
      labels:
        app: mediciclient
    spec:
      containers:
        - name: mediciclient
          image: thembaembot/mediciclient:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mediciclient
spec:
  selector:
    app: mediciclient
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer